/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 16c3129c217ba2f449a2424d16895661)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "ChatAgent";
	}
	interface Env {
		AI_SEARCH: AiSearchNamespace;
		AI: Ai;
		ChatAgent: DurableObjectNamespace<import("./src/server").ChatAgent>;
	}
}
interface Env extends Cloudflare.Env {}
