/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: e4676a293701a7d0b4140c5d8b009369)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "ChatAgent" | "VoiceChatAgent";
	}
	interface Env {
		AI_SEARCH: AiSearchNamespace;
		AI: Ai;
		ChatAgent: DurableObjectNamespace<import("./src/server").ChatAgent>;
		VoiceChatAgent: DurableObjectNamespace<import("./src/server").VoiceChatAgent>;
	}
}
interface Env extends Cloudflare.Env {}
